name: mobile
description: Horse Racing Prediction — mobile app
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.11.5

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  http: ^1.2.2
  shared_preferences: ^2.3.3
  intl: ^0.19.0
  socket_io_client: ^2.0.3+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/horse-racing-track.jpg
    - assets/images/spectator-hero.jpg
    - assets/images/jockey-hero.jpg
    - assets/images/horse-racing-hero.jpg
    - assets/images/admin-tournaments-hero.jpg
    - assets/images/dua-ngua-duong-bang.jpg
    - assets/images/anh-dua-ngua-7.jpg
